# NOTE: update this with your service name
service: digiroad-lambda-assetmatcher

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    PGDATABASE: ${env:RDS_DATABASE}
    PGHOST: ${env:RDS_HOST}
    PGPORT: ${env:RDS_PORT,'5432'}
    PGUSER: ${env:RDS_USER}
    PGPASSWORD: ${env:RDS_PASSWORD}

functions:
  convert: # original
    handler: lambdas/create.main
    events:
      - http:
          path: convert
          cors: true
          method: post

  queryDataset: # original
    handler: lambdas/queryDataset.main
    events:
      - http:
          path: queryDataset
          cors: true
          method: get

  create:
    handler: lambdas/create.main
    events:
      - http:
          path: dataset
          cors: true
          method: post

  get:
    handler: lambdas/get.main
    events:
      - http:
          path: dataset/{id}
          cors: true
          method: get

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
